python starter.py --dataset "Weights_combine_stretch" \
                        --data_dir "./data" \
                        --pkl "./checkpoint/Weights_combine_stretch_pix_256_batch_16_embed_52_label_51/Weights_combine_stretch" \
                        --batch_size 1 \
                        --data_size -1 \
                        --z_dim 52 \
                        --y_dim 51 \
                        --pix_dim 256 \
                        --gpus 1 \
                        --worker 48 \
                        --testmode
