python starter.py --dataset "L1_CLS_patchD" \
                        --data_dir "./data" \
                        --epoch 5000 \
                        --batch_size 22 \
                        --data_size -1 \
                        --z_dim 51 \
                        --pix_dim 256 \
                        --gpus 0,1 \
                        --worker 48 \
                        --lrG 5e-5 \
                        --resume
